### ISSUE TITLE
Simple Covers Hollow Covers block Mekanism cable connections

### ISSUE THREAD

**Issue by Xiaminou** [bdew/covers#15] opened 2016-12-03 17:11 UTC
Here is with Chisel and Bits:
![2016-12-03_18 05 18](https://cloud.githubusercontent.com/assets/8670392/20860927/d3816a8e-b983-11e6-84b9-db312a1451d2.png)

Simple Covers (no energy flowing throught):
![2016-12-03_18 05 46](https://cloud.githubusercontent.com/assets/8670392/20860929/e245d9a6-b983-11e6-8adf-4b9f2f9d12b8.png)

**Comment by bdew** [comment] 2016-12-04 18:55
There's something weird with how Mek detects connections with MCMP parts. I've seen this already but didn't get the chance to investigate in depth. It's very likely that the problem is on their side.

**Comment by Xiaminou** [comment] 2016-12-04 21:02
Yeah I would say so because it worked if you use cover strips and stuff like that instead of hollow covers.

**Comment by bdew** [comment] 2017-10-12 16:51
I'm closing this issue as part of a spring cleaning of my issue trackers from old stuff.

If you believe it's a bug that is still relevant in Minecraft 1.12 - Feel free to reopen it.

**Closed as completed by bdew** 2017-10-12 16:51 UTC
